
[package]
name = "mtxdb-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"
repository = "https://github.com/Wombat-Foundation/mtxdb"
description = "mtxdb: core components and methods"
license = "MIT OR Apache-2.0"
authors = ["Shane Jaroch <chown_tee@proton.me>"]
keywords = ["database", "matrix", "packfile", "content-addressed", "hamt"]
categories = ["database-implementations", "storage"]
