[package]
name = "mtxdb-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"
publish = false

[workspace]

[[bin]]
name = "mtxdb"
path = "src/main.rs"

[dependencies]
clap = { version = "=4.5.48", features = ["derive", "env"] }
anyhow = "1.0"
hex = "0.4"
mtxdb = { path = ".." }
bytes = "1.5"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
arithmetic_side_effects = "warn"
dbg_macro = "warn"
get_unwrap = "warn"
str_to_string = "warn"
